### ISSUE TITLE
Combine test values from ISO 2533 into full test file

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/atmospheric#17]
We need to move the values of the ISO 2533 tables into the test structure (`tests.yml`):
* iso-2533-1975-table5.yaml
* iso-2533-1975-table6.yaml
* iso-2533-1975-table7.yaml

_Originally posted by @ronaldtse in https://github.com/metanorma/atmospheric/issues/15#issuecomment-1933292174_

**Comment by newbthenewbd** [comment]
Just noticed the missing mmHg values, tripped up my script for a while... :) I suppose these just don't get tested, or do we try to convert from mbar, or...?

**Comment by newbthenewbd** [comment]
These tables have it pretty crazy...
```
  - geometrical-altitude: 300
    geopotential-altitude: 300
    temperature-K: 286200
    temperature-C: 13050
    p-mbar: 9.77727e+2
    p-mmHg: 7.33356e+2
    density: 1.19011e+0
    acceleration: 9.8057
```
vs
```
  - geopotential-altitude: 300
    geometrical-altitude: 300
    temperature-K: 286200
    temperature-C: 13050
    p-mbar: 9.77725e+2
    p-mmHg: 7.33355e+2
    density: 1.19011e+0
    acceleration: 9.8057
```
