### ISSUE TITLE
Add ISO 2533:1975/ADD 1:1985 calculations

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/atmospheric#26]
<img width="602" alt="Screenshot 2024-02-12 at 2 19 00 AM" src="https://github.com/metanorma/atmospheric/assets/11865/cd36cfee-aafb-4de0-9e59-51aa447b0bdc">
<img width="607" alt="Screenshot 2024-02-12 at 2 19 11 AM" src="https://github.com/metanorma/atmospheric/assets/11865/adb850dc-5211-4920-8130-45eaaa5fcab0">
<img width="606" alt="Screenshot 2024-02-12 at 2 19 38 AM" src="https://github.com/metanorma/atmospheric/assets/11865/fd0f171d-b04b-4d4f-85e8-bb61938f9a14">
<img width="600" alt="Screenshot 2024-02-12 at 2 19 46 AM" src="https://github.com/metanorma/atmospheric/assets/11865/738483e2-f93f-4cfa-9f29-da15f21568f2">

## Table 1
<img width="601" alt="Screenshot 2024-02-12 at 2 20 17 AM" src="https://github.com/metanorma/atmospheric/assets/11865/85771941-b70a-4561-8b03-c15148a5de5c">

...

<img width="597" alt="Screenshot 2024-02-12 at 2 20 32 AM" src="https://github.com/metanorma/atmospheric/assets/11865/d779f7bf-d63f-479b-aaa3-e2081825d432">

## Table 2
<img width="598" alt="Screenshot 2024-02-12 at 2 20 46 AM" src="https://github.com/metanorma/atmospheric/assets/11865/f4c2782d-be93-49b4-9d5f-f98702e7fec3">
...
<img width="537" alt="Screenshot 2024-02-12 at 2 21 11 AM" src="https://github.com/metanorma/atmospheric/assets/11865/e8b4e864-1bbd-47c1-aaf5-ce7f80fe3ce4">

## Table 3

<img width="599" alt="Screenshot 2024-02-12 at 2 21 24 AM" src="https://github.com/metanorma/atmospheric/assets/11865/55c53bd3-a1e3-4a0e-af86-88ddf3718f59">
...
<img width="586" alt="Screenshot 2024-02-12 at 2 21 35 AM" src="https://github.com/metanorma/atmospheric/assets/11865/2b221861-654e-4d54-b3b0-ec91e537ece7">

## Table 4
<img width="602" alt="Screenshot 2024-02-12 at 2 21 44 AM" src="https://github.com/metanorma/atmospheric/assets/11865/737e2da2-5799-4564-930f-35c4f9220a33">
...
<img width="535" alt="Screenshot 2024-02-12 at 2 22 04 AM" src="https://github.com/metanorma/atmospheric/assets/11865/3cf43359-11c8-4da5-aee1-318932c63e0e">

## Table 5
<img width="557" alt="Screenshot 2024-02-12 at 2 22 11 AM" src="https://github.com/metanorma/atmospheric/assets/11865/3d418c75-aa0b-4b7e-a037-ca2224551a9c">
...
<img width="548" alt="Screenshot 2024-02-12 at 2 22 27 AM" src="https://github.com/metanorma/atmospheric/assets/11865/b2228cb3-7a01-4670-a84a-1be8e7fe38ec">

## Table 6
<img width="590" alt="Screenshot 2024-02-12 at 2 22 48 AM" src="https://github.com/metanorma/atmospheric/assets/11865/665e4fd7-6786-49a3-93d5-57525cd362ab">
...
<img width="539" alt="Screenshot 2024-02-12 at 2 23 09 AM" src="https://github.com/metanorma/atmospheric/assets/11865/094b3ddd-ee86-42eb-9159-b3f6526f13cb">

**Comment by newbthenewbd** [comment]
It seems that basically, this addendum just needs another round of tables generated (and perhaps a test if these derived formulae might be more accurate nonetheless), whereas the other, addendum-2, a conversion procedure from meters to feet? Not much, still took me a few reads :)

So gonna fetch them from https://github.com/metanorma/iso-2533 and adjust the generator soon, I guess that it's gonna go in the same pull request #31...

**Comment by newbthenewbd** [comment]
Hmm, looks like these addendum tables are not such nice yaml... Or are they supposed to look the way they do?

**Comment by ronaldtse** [comment]
@newbthenewbd indeed, we need to update how these tables are encoded...
