### ISSUE TITLE
Add optional "high-precision" processing mode

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/atmospheric#34]
This project is starting now, and we will need a mode that generates values of higher precision.

By higher precision I was just thinking of BigNumber, not some fancy way of reimplementing floats.

@newbthenewbd would you be able to handle this?

**Comment by newbthenewbd** [comment]
So that BigDecimal from earlier, but toggleable from within the code, this time? Well, got that foot in the door :)

**Comment by ronaldtse** [comment]
We can use a static class switch such as `Atmospheric::Isa.set_precision(:high)` to make the change.

**Comment by newbthenewbd** [comment]
Just as an aside, that new `measured` dependency hauls along a couple others, among them `activesupport`, which apparently may conflict with the latest json gem on some systems... like mine :joy:

Got an error like that, and had to downgrade ruby-json: https://gitlab.archlinux.org/archlinux/packaging/packages/wpscan/-/issues/1

So, if it's to remain just for ft<->m conversions, that dependency might be a bit of an overkill?

**Comment by ronaldtse** [comment]
@newbthenewbd oh no I did not realize `activesupport` became a dependency. Let's use another "meter to foot" conversion gem/mechanism.
